const db = require('../database/db');

const now = new Date().toISOString();

const dishes = [
  // ═══════════════════════════════════════════
  // 🍲 ENTRÉES (entree)
  // ═══════════════════════════════════════════
  { id:101, emoji:'🥣', image:'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop', name:'Soupe de Tomate Malgache', desc:'Tomate fraîche, oignon, coriandre', price:2500, available:true, platJour:false, category:'entree', tags:'Entrées,Soupes,Cuisine malgache,Végétarien,Déjeuner,Non épicé' },
  { id:102, emoji:'🥗', image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop', name:'Salade d\'Avocat Tropical', desc:'Avocat, tomate, citron vert, oignon', price:3500, available:true, platJour:false, category:'entree', tags:'Entrées,Salades,Cuisine malgache,Végétarien,Végan,Sans gluten,Déjeuner,Non épicé' },
  { id:103, emoji:'🥬', image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop', name:'Brèdes Mafana', desc:'Épinards épicés à la sauce tomate', price:3000, available:true, platJour:false, category:'entree', tags:'Entrées,Salades,Cuisine malgache,Végétarien,Végan,Épicé,Déjeuner' },
  { id:104, emoji:'🦀', image:'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&h=300&fit=crop', name:'Salade de Crabe', desc:'Crabe frais, avocat, citron vert', price:8000, available:true, platJour:false, category:'entree', tags:'Entrées,Salades,Poissons et fruits de mer,Cuisine malgache,Peu épicé,Dîner' },
  { id:105, emoji:'🥟', image:'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop', name:'Samoussas Viande', desc:'Chausson farci au bœuf épicé (x4)', price:3000, available:true, platJour:false, category:'entree', tags:'Entrées,Viandes,Cuisine malgache,Épicé,Snack,Apéritif' },
  { id:106, emoji:'🐟', image:'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400&h=300&fit=crop', name:'Bouchées de Thon', desc:'Beignets de thon croustillants (x6)', price:4500, available:true, platJour:false, category:'entree', tags:'Entrées,Poissons et fruits de mer,Cuisine malgache,Peu épicé,Snack,Apéritif' },
  { id:107, emoji:'🥣', image:'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop', name:'Soupe de Lentilles', desc:'Lentilles corail, carottes, cumin', price:2500, available:true, platJour:false, category:'entree', tags:'Entrées,Soupes,Cuisine malgache,Végétarien,Végan,Déjeuner,Non épicé' },
  { id:108, emoji:'🥒', image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', name:'Gaspacho Malgache', desc:'Soupe froide de concombre et menthe', price:3000, available:true, platJour:false, category:'entree', tags:'Entrées,Soupes,Cuisine malgache,Végétarien,Végan,Sans gluten,Peu épicé,Déjeuner' },
  { id:109, emoji:'🧅', image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', name:'Oignons Farcis', desc:'Oignons farcis au riz et herbes', price:3500, available:true, platJour:false, category:'entree', tags:'Entrées,Végétarien,Cuisine malgache,Non épicé,Déjeuner' },
  { id:110, emoji:'🥕', image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', name:'Salade de Carottes Râpées', desc:'Carottes, citron, huile d\'olive', price:2000, available:true, platJour:false, category:'entree', tags:'Entrées,Salades,Cuisine malgache,Végétarien,Végan,Sans gluten,Non épicé' },

  // ═══════════════════════════════════════════
  // 🍛 PLATS PRINCIPAUX (plat)
  // ═══════════════════════════════════════════
  { id:201, emoji:'🥘', image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', name:'Romazava', desc:'Le plat national : viande, brèdes, tomate', price:7000, available:true, platJour:true, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Meilleures ventes,Recommandations du chef,Déjeuner' },
  { id:202, emoji:'🍖', image:'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', name:'Hen\'omby Ritra', desc:'Bœuf mijoté aux épices malgaches', price:8500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Meilleures ventes,Déjeuner' },
  { id:203, emoji:'🍛', image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop', name:'Hen\'omby sy Sakamalao', desc:'Bœuf sauté à l\'ail et gingembre', price:8000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Déjeuner' },
  { id:204, emoji:'🍗', image:'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop', name:'Akoho sy Voanio', desc:'Poulet au lait de coco, vanille', price:7500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poulet,Cuisine malgache,Peu épicé,Meilleures ventes,Déjeuner' },
  { id:205, emoji:'🐷', image:'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', name:'Henakisoa sy Anamalao', desc:'Porc grillé à la sauce arachide', price:7000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Déjeuner' },
  { id:206, emoji:'🐟', image:'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400&h=300&fit=crop', name:'Saucisse de Poisson Grillée', desc:'Saucisse de poisson, riz, salade', price:6000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poissons et fruits de mer,Cuisine malgache,Peu épicé,Déjeuner' },
  { id:207, emoji:'🍛', image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop', name:'Hen\'omby Sauce Tomate', desc:'Bœuf mijoté à la tomate fraîche', price:7500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Peu épicé,Déjeuner' },
  { id:208, emoji:'🍲', image:'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop', name:'Vary amin\'ny Hen\'omby', desc:'Riz au bœuf et légumes', price:6000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Riz,Cuisine malgache,Peu épicé,Déjeuner' },
  { id:209, emoji:'🍛', image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop', name:'Voanio Hen\'omby', desc:'Bœuf à la noix de coco et curcuma', price:8500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Recommandations du chef,Dîner' },
  { id:210, emoji:'🥘', image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', name:'Ravimbary', desc:'Riz au lait de coco sucré', price:5000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Riz,Cuisine malgache,Végétarien,Non épicé,Déjeuner' },
  { id:211, emoji:'🦐', image:'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop', name:'Crevettes à l\'Ail', desc:'Crevettes sautées à l\'ail et beurre', price:12000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poissons et fruits de mer,Cuisine malgache,Peu épicé,Recommandations du chef,Dîner' },
  { id:212, emoji:'🐙', image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', name:'Ozaka sy Voanio', desc:'Poulpe sauce coco, riz parfumé', price:10000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poissons et fruits de mer,Cuisine malgache,Peu épicé,Dîner' },
  { id:213, emoji:'🥩', image:'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', name:'Steak de Bœuf Grillé', desc:'Bœuf grillé, légumes, sauce au poivre', price:15000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine française,Épicé,Meilleures ventes,Dîner' },
  { id:214, emoji:'🍗', image:'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop', name:'Poulet Yassa', desc:'Poulet mariné citron, oignons caramélisés', price:8500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poulet,Cuisine africaine,Épicé,Meilleures ventes,Déjeuner' },
  { id:215, emoji:'🍛', image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop', name:'Curry de Poulet Indien', desc:'Poulet au curry, lait de coco, riz basmati', price:8000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poulet,Cuisine indienne,Épicé,Recommandations du chef,Déjeuner' },
  { id:216, emoji:'🍝', image:'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=300&fit=crop', name:'Pâtes Carbonara', desc:'Pâtes, lardons, crème, parmesan', price:7000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Pâtes,Cuisine italienne,Non épicé,Déjeuner' },
  { id:217, emoji:'🍕', image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop', name:'Pizza Margherita', desc:'Tomate, mozzarella, basilic frais', price:8000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Pizza,Cuisine italienne,Végétarien,Non épicé,Déjeuner,Snack' },
  { id:218, emoji:'🍔', image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop', name:'Burger Classique', desc:'Bœuf, cheddar, salade, tomate, sauce', price:9000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Burgers,Cuisine américaine,Peu épicé,Meilleures ventes,Déjeuner,Snack' },
  { id:219, emoji:'🌮', image:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop', name:'Tacos au Bœuf', desc:'Bœuf épicé, guacamole, crème, fromage', price:7500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine mexicaine,Épicé,Meilleures ventes,Déjeuner,Snack' },
  { id:220, emoji:'🍣', image:'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop', name:'Sushi Mix (8 pièces)', desc:'Saumon, thon, crevette, avocat', price:15000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poissons et fruits de mer,Cuisine japonaise,Non épicé,Recommandations du chef,Dîner' },
  { id:221, emoji:'🥘', image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', name:'Kitoza', desc:'Bœuf séché et grillé, riz, condiments', price:7000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Épicé,Meilleures ventes,Déjeuner' },
  { id:222, emoji:'🐟', image:'https://images.unsplash.com/photo-1534766555764-ce878a5e3a2b?w=400&h=300&fit=crop', name:'Poisson Rouge Grillé', desc:'Poisson entier grillé aux épices', price:9000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Poissons et fruits de mer,Cuisine malgache,Épicé,Déjeuner' },
  { id:223, emoji:'🍛', image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop', name:'Risotto aux Champignons', desc:'Riz crémeux, champignons, parmesan', price:7500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Riz,Cuisine italienne,Végétarien,Non épicé,Déjeuner' },
  { id:224, emoji:'🥘', image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', name:'Tongolo sy Masaka', desc:'Oignons frits au bœuf, riz', price:6500, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine malgache,Peu épicé,Déjeuner' },
  { id:225, emoji:'🍖', image:'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', name:'Côtes de Bœuf Grillées', desc:'Côtes de bœuf marinées, frites', price:18000, available:true, platJour:false, category:'plat', tags:'Plats principaux,Viandes,Cuisine française,Épicé,Recommandations du chef,Dîner' },

  // ═══════════════════════════════════════════
  // 🍚 ACCOMPAGNEMENTS (accomp)
  // ═══════════════════════════════════════════
  { id:301, emoji:'🍚', image:'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop', name:'Riz Blanc', desc:'Riz basmati cuit à la perfection', price:1500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Riz,Cuisine malgache,Végétarien,Végan,Non épicé' },
  { id:302, emoji:'🍟', image:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop', name:'Frites de Patates', desc:'Patates douces frites croustillantes', price:2000, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
  { id:303, emoji:'🫓', image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop', name:'Mofo Sakay', desc:'Beignets pimentés traditionnels', price:1000, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Épicé,Petit-déjeuner,Snack' },
  { id:304, emoji:'🥑', image:'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=300&fit=crop', name:'Salade Verte', desc:'Mesclun, concombre, vinaigrette', price:2500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Salades,Cuisine malgache,Végétarien,Végan,Sans gluten,Non épicé' },
  { id:305, emoji:'🍞', image:'https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&h=300&fit=crop', name:'Pain Maison', desc:'Pain frais sorti du four', price:500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Non épicé,Petit-déjeuner' },
  { id:306, emoji:'🧈', image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop', name:'Manioc Frit', desc:'Manioc croustillant, sauce piment', price:2000, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Épicé,Snack' },
  { id:307, emoji:'🫘', image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', name:'Lentilles Saumonées', desc:'Lentilles cuites aux épices douces', price:2000, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Végan,Sans gluten,Peu épicé' },
  { id:308, emoji:'🥒', image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop', name:'Concombre Citronné', desc:'Concombre frais au citron vert', price:1500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Salades,Cuisine malgache,Végétarien,Végan,Sans gluten,Non épicé' },
  { id:309, emoji:'🌽', image:'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop', name:'Maïs Grillé', desc:'Maïs grillé au beurre et sel', price:1500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
  { id:310, emoji:'🧅', image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', name:'Oignons Confités', desc:'Oignons caramélisés au vinaigre balsamique', price:1500, available:true, platJour:false, category:'accomp', tags:'Accompagnements,Cuisine française,Végétarien,Végan,Non épicé' },

  // ═══════════════════════════════════════════
  // 🍰 DESSERTS (dessert)
  // ═══════════════════════════════════════════
  { id:401, emoji:'🍌', image:'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=300&fit=crop', name:'Akondro Mafana', desc:'Banane flambée à la cannelle', price:2500, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé,Snack' },
  { id:402, emoji:'🥭', image:'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop', name:'Salade de Fruits Tropicale', desc:'Mangue, papaye, ananas, fruit de la passion', price:3000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Végan,Sans gluten,Non épicé' },
  { id:403, emoji:'🍮', image:'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop', name:'Flan à la Vanille', desc:'Flan onctueux à la vanille de Madagascar', price:3000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé' },
  { id:404, emoji:'🍫', image:'https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&h=300&fit=crop', name:'Fondant au Chocolat', desc:'Chocolat de Madagascar, cœur coulant', price:4000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine française,Végétarien,Non épicé,Recommandations du chef' },
  { id:405, emoji:'🍦', image:'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=300&fit=crop', name:'Glace Mangue-Passion', desc:'Glace artisanale mangue et fruit de la passion', price:2500, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé,Snack' },
  { id:406, emoji:'🍰', image:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop', name:'Tarte aux Fruits', desc:'Pâte sablée, crème pâtissière, fruits frais', price:4500, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine française,Végétarien,Non épicé' },
  { id:407, emoji:'🧁', image:'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=400&h=300&fit=crop', name:'Muffin Coco-Vanille', desc:'Muffin moelleux à la noix de coco', price:2000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé,Snack,Petit-déjeuner' },
  { id:408, emoji:'🍨', image:'https://images.unsplash.com/photo-1488900128323-21503983a07e?w=400&h=300&fit=crop', name:'Koba Akondro', desc:'Dessert traditionnel aux bananes et arachides', price:3000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé,Recommandations du chef' },
  { id:409, emoji:'🥤', image:'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop', name:'Smoothie Bowl', desc:'Açaï, banane, granola, fruits frais', price:5000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Végan,Sans gluten,Non épicé,Petit-déjeuner' },
  { id:410, emoji:'🍡', image:'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=300&fit=crop', name:'Bonbons Cracras', desc:'Bonbons traditionnels à la noix de coco', price:2000, available:true, platJour:false, category:'dessert', tags:'Desserts,Cuisine malgache,Végétarien,Non épicé,Snack' },

  // ═══════════════════════════════════════════
  // 🥤 BOISSONS (boisson)
  // ═══════════════════════════════════════════
  { id:501, emoji:'🥤', image:'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=300&fit=crop', name:'Jus de Mangue', desc:'Jus frais de mangue locale', price:2000, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
  { id:502, emoji:'🍹', image:'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&h=300&fit=crop', name:'Cocktail Passion-Vanille', desc:'Fruit de la passion, vanille, glace', price:4000, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Non épicé,Apéritif' },
  { id:503, emoji:'☕', image:'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop', name:'Café Malgache', desc:'Café des Hauts Plateaux, intense et aromatique', price:1500, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé,Petit-déjeuner' },
  { id:504, emoji:'🍵', image:'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', name:'Thé Vert Menthe', desc:'Thé vert à la menthe fraîche', price:1500, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé' },
  { id:505, emoji:'🍺', image:'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400&h=300&fit=crop', name:'THB Lager', desc:'Bière malgache blonde, fraîche et légère', price:3000, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Non épicé,Apéritif' },
  { id:506, emoji:'🍷', image:'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop', name:'Vin Ranofary', desc:'Vin rouge de la côte est, fruité', price:8000, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Non épicé,Dîner' },
  { id:507, emoji:'🧃', image:'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=300&fit=crop', name:'Jus de Litchi', desc:'Jus de litchi frais, sucré et parfumé', price:2500, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
  { id:508, emoji:'🥤', image:'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=300&fit=crop', name:'Groseille Pressée', desc:'Jus de groseille, acidulé et rafraîchissant', price:2000, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
  { id:509, emoji:'💧', image:'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=400&h=300&fit=crop', name:'Eau Minérale', desc:'Eau plate ou gazeuse 50cl', price:1000, available:true, platJour:false, category:'boisson', tags:'Boissons,Végétarien,Végan,Non épicé' },
  { id:510, emoji:'🥛', image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop', name:'Lait de Coco Frais', desc:'Lait de coco frais, légèrement sucré', price:2500, available:true, platJour:false, category:'boisson', tags:'Boissons,Cuisine malgache,Végétarien,Végan,Non épicé,Snack' },
];

// Clear existing dishes and insert new ones
db.get('dishes').remove().write();
dishes.forEach(d => {
  d.createdAt = now;
  db.get('dishes').push(d).write();
});

console.log(`[SEED] ${dishes.length} plats ajoutés au menu !`);
